#! /usr/bin/env python
# encoding: utf-8

'''
@author: Milos Subotic <milos.subotic.sm@gmail.com>
@license: MIT

'''

###############################################################################

import os
import sys
import fnmatch
import shutil
import datetime
import glob

import waflib

from os.path import join

###############################################################################

APPNAME = 'plate_detection'

top = '.'

###############################################################################

programs_for_test = [
	'ball_detection',
	'cherry_detection',
]

programs_for_install = [
	'ball_uart_chassis',
]

def prerequisites(ctx):
	if sys.platform.startswith('linux'):
		# Ubuntu.
		ctx.exec_command2(
			'apt -y install libopencv-dev libtesseract-dev ' + \
				'tesseract-ocr-srp-latn'
		)
		# For examples:
		# apt -y install opencv-doc
	elif sys.platform == 'win32' and os.name == 'nt' and os.path.sep == '/':
		# MSYS2 Windows /mingw32/bin/python.
		ctx.exec_command2(
			'pacman --noconfirm -S mingw-w64-i686-???'
		)

def options(opt):
	opt.load('gcc gxx')
	opt.recurse('Utils')
	opt.recurse('OpenCV_Utils')
	
	opt.add_option(
		'--app',
		dest = 'app',
		default = None,
		help = 'App to be run'
	)
	
def configure(cfg):
	cfg.load('gcc gxx')
	cfg.recurse('Utils')
	cfg.recurse('OpenCV_Utils')
	
	cfg.check_cfg(
		package = 'tesseract',
		uselib_store = 'tesseract',
		args = '--cflags --libs',
		mandatory = True
	)
	
	cfg.env.append_value('CXXFLAGS', '-std=c++11')
	#cfg.env.append_value('LIB', 'pthread')
	cfg.env.append_value('CXXFLAGS', '-g -rdynamic'.split()) # For debug.

def build(bld):
	bld.recurse('Utils')
	bld.recurse('OpenCV_Utils')
	
	bld.program(
		features = 'cxx',
		source = bld.path.ant_glob('src/*.cpp'),
		use = 'Utils OpenCV_Utils tesseract',
		target = 'plate_detection',
		install_path = False
	)

def postinstall(ctx):
	# Reload systemd, enable, then start the service.
	ctx.exec_command2('systemctl --system daemon-reload')
	for p in programs_for_install:
		n = service_name(p)
		ctx.exec_command2('systemctl enable ' + n)
		ctx.exec_command2('systemctl start ' + n)

def services_log(ctx):
	for p in programs_for_install:
		n = service_name(p)
		ctx.exec_command2('systemctl status ' + n)
		
def services_stop(ctx):
	for p in programs_for_install:
		n = service_name(p)
		ctx.exec_command2('systemctl stop ' + n)


def run(ctx):
	'''./waf run --app=<NAME>'''
	if ctx.options.app:
		a = ctx.options.app
	else:
		a = 'plate_detection'

	if sys.platform == 'win32':
		# MSYS2
		ctx.exec_command2('build\\' + a)
	else:
		ctx.exec_command2('./build/' + a)

###############################################################################

def exec_command2(self, cmd, **kw):
	# Log output while running command.
	kw['stdout'] = None
	kw['stderr'] = None
	ret = self.exec_command(cmd, **kw)
	if ret != 0:
		self.fatal('Command "{}" returned {}'.format(cmd, ret))
setattr(waflib.Context.Context, 'exec_command2', exec_command2)

###############################################################################

def recursive_glob(pattern, directory = '.'):
	for root, dirs, files in os.walk(directory, followlinks = True):
		for f in files:
			if fnmatch.fnmatch(f, pattern):
				yield os.path.join(root, f)
		for d in dirs:
			if fnmatch.fnmatch(d + '/', pattern):
				yield os.path.join(root, d)

def collect_git_ignored_files():
	for gitignore in recursive_glob('.gitignore'):
		with open(gitignore) as f:
			base = os.path.dirname(gitignore)
			
			for pattern in f.readlines():
				pattern = pattern[:-1]
				for f in recursive_glob(pattern, base):
					yield f

###############################################################################

def distclean(ctx):
	for fn in collect_git_ignored_files():
		if os.path.isdir(fn):
			shutil.rmtree(fn)
		else:
			os.remove(fn)

def dist(ctx):
	now = datetime.datetime.now()
	time_stamp = '{:d}-{:02d}-{:02d}-{:02d}-{:02d}-{:02d}'.format(
		now.year,
		now.month,
		now.day,
		now.hour,
		now.minute,
		now.second
	)
	ctx.arch_name = '../{}-{}.zip'.format(APPNAME, time_stamp)
	ctx.algo = 'zip'
	ctx.base_name = APPNAME
	# Also pack git.
	waflib.Node.exclude_regs = waflib.Node.exclude_regs.replace(
'''
**/.git
**/.git/**
**/.gitignore''', '')
	# Ignore waf's stuff.
	waflib.Node.exclude_regs += '\n**/.waf*'
	
###############################################################################
